"""Write docs/openapi.yaml from the FastAPI app. `make openapi`; tests/contract/test_openapi.py fails on drift."""
from __future__ import annotations

import sys

import yaml

from harness.checklists import ROOT
from services.api.main import app


def main() -> int:
    doc = app.openapi()
    out = ROOT / "docs" / "openapi.yaml"
    out.write_text("# Generated by `make openapi` from services/api/main.py. Do not edit by hand.\n" + yaml.safe_dump(doc, sort_keys=False, allow_unicode=True), encoding="utf-8")
    print(f"openapi: {len(doc['paths'])} paths -> {out.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
