"""Regenerate STATUS.md from the checklists and the tests they name.

Usage: python -m harness.status [--no-tests]

One row per checklist component: owner, spec sections, checkbox completion, last test result. Tests
listed as pytest paths are run (junit XML under eval/runs/) when the path exists; `make <target>`
entries are reported as delegated to `make verify`. Date only in the footer, so re-running on the same
day is a no-op for git.
"""
from __future__ import annotations

import argparse
import subprocess
import sys
import xml.etree.ElementTree as ET
from datetime import date
from pathlib import Path

from harness.checklists import ROOT, Checklist, load_all

STATUS = ROOT / "STATUS.md"
JUNIT = ROOT / "eval" / "runs" / "junit.xml"


def _pytest_targets(cl: Checklist) -> tuple[list[str], list[str]]:
    """Split checklist tests into (existing pytest paths, missing pytest paths). Make targets are excluded."""
    existing, missing = [], []
    for t in cl.tests:
        if t.startswith("make "):
            continue
        path = t.split("::", 1)[0]
        (existing if (ROOT / path).exists() else missing).append(t)
    return existing, missing


def _parse_junit(path: Path) -> tuple[int, int, int, int]:
    """Return (tests, failures, errors, skipped) summed over all testsuites."""
    root = ET.parse(path).getroot()
    suites = [root] if root.tag == "testsuite" else list(root.iter("testsuite"))
    t = f = e = s = 0
    for suite in suites:
        t += int(suite.get("tests", 0))
        f += int(suite.get("failures", 0))
        e += int(suite.get("errors", 0))
        s += int(suite.get("skipped", 0))
    return t, f, e, s


def run_tests(cl: Checklist, run: bool = True) -> str:
    existing, missing = _pytest_targets(cl)
    make_targets = [t for t in cl.tests if t.startswith("make ")]
    notes: list[str] = []
    if existing and run:
        JUNIT.parent.mkdir(parents=True, exist_ok=True)
        if JUNIT.exists():
            JUNIT.unlink()
        cmd = [sys.executable, "-m", "pytest", "-q", "-p", "no:cacheprovider", f"--junitxml={JUNIT}", *existing]
        proc = subprocess.run(cmd, capture_output=True, text=True, cwd=ROOT)
        if JUNIT.exists():
            t, f, e, s = _parse_junit(JUNIT)
            if t == 0:
                notes.append("no tests collected")
            else:
                verdict = "green" if (f + e) == 0 else "RED"
                notes.append(f"{verdict}: {t - f - e - s} passed, {f + e} failed, {s} skipped")
        else:
            notes.append(f"pytest exit {proc.returncode}, no junit output")
    elif existing:
        notes.append("not run (--no-tests)")
    if missing:
        notes.append(f"no tests yet ({', '.join(missing)})")
    if make_targets:
        notes.append("via " + ", ".join(f"`{t}`" for t in make_targets))
    return "; ".join(notes) if notes else "no tests yet"


def render(rows: list[tuple[Checklist, str]]) -> str:
    lines = [
        "# STATUS",
        "",
        "One row per component (DECISIONS §17.3). Checklist counts are the ticked boxes in",
        "`harness/checklists/<component>.md`; the Reviewer ticks reviewer-verified items with evidence.",
        "Refresh with `make status` (runs the tests each checklist names and rewrites this file).",
        "",
        "| Component | Owner | Spec | Checklist | Last test result |",
        "|---|---|---|---|---|",
    ]
    for cl, result in rows:
        spec = ", ".join(f"§{s}" for s in cl.spec_sections)
        lines.append(f"| [{cl.title}](harness/checklists/{cl.component}.md) | {cl.owner} | {spec} | {cl.done} of {cl.total} | {result} |")
    done = sum(cl.done for cl, _ in rows)
    total = sum(cl.total for cl, _ in rows)
    lines += [
        "",
        f"Overall checklist completion: {done} of {total}. `make verify` is the only definition of done;",
        "this board is a summary, not a gate.",
        "",
        f"generated by make status on {date.today().isoformat()}",
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--no-tests", action="store_true", help="do not run pytest; report checklist counts only")
    ap.add_argument("--out", default=str(STATUS))
    args = ap.parse_args(argv)
    rows = [(cl, run_tests(cl, run=not args.no_tests)) for cl in load_all().values()]
    Path(args.out).write_text(render(rows), encoding="utf-8")
    red = [cl.component for cl, r in rows if r.startswith("RED")]
    print(f"status: wrote {args.out} ({len(rows)} components{'; RED: ' + ', '.join(red) if red else ''})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
